### ISSUE TITLE
Omnik inverter geen weergave

### ISSUE THREAD

**Issue by Arnaudarduino** [sincze/Domoticz-Omnik-Local-Web-Plugin#10]
I get this failure, and no kwh and w in Domoticz

This what in the log problem
2021-04-05 14:56:56.708 Error: Feithzonnig hardware (22) thread seems to have ended unexpectedly

Whit ip/js/status.js i get this, so there is value

`var version= "H4.01.51MW.2.01W1.0.65(2018-02-271-D)";
var m2mMid = "644401429";
var wlanMac= "F0:FE:6B:E4:EB:64";
var m2mRssi= "100%";
var wanIp= "192.168.2.251";
var nmac= "F0FE6BE4EB67";
var fephy= "off";
var yz_device_type="258";
var yz_device_num="1";
var init_inv_type="0";
var myDeviceArray=new Array();
myDeviceArray[0]="AANN302019184099,V5.04Build230,V4.13Build262,Omnik3000tl ,3000,976,136,17685,,1,";

var version= "H4.01.51MW.2.01W1.0.65(2018-02-271-D)";
var m2mMid = "644401429";
var wlanMac= "F0:FE:6B:E4:EB:64";
var m2mRssi= "100%";
var wanIp= "192.168.2.251";
var nmac= "F0FE6BE4EB67";
var fephy= "off";
var yz_device_type="258";
var yz_device_num="1";
var init_inv_type="0";
var myDeviceArray=new Array();
myDeviceArray[0]="AANN302019184099,V5.04Build230,V4.13Build262,Omnik3000tl ,3000,2160,160,17688,,0,";

var version= "H4.01.51MW.2.01W1.0.65(2018-02-271-D)";
var m2mMid = "644401429";
var wlanMac= "F0:FE:6B:E4:EB:64";
var m2mRssi= "100%";
var wanIp= "192.168.2.251";
var nmac= "F0FE6BE4EB67";
var fephy= "off";
var yz_device_type="258";
var yz_device_num="1";
var init_inv_type="0";
var myDeviceArray=new Array();
myDeviceArray[0]="AANN302019184099,V5.04Build230,V4.13Build262,Omnik3000tl ,3000,2845,523,17724,,0,";

This the info from my inverter

Device information
Device serial number644401429
Firmware versionH4.01.51MW.2.01W1.0.65(2018-02-271-D)
Wireless AP modeEnable
SSIDAP_644401429
IP address10.10.100.254
MAC addressF0:FE:6B:E4:EB:64
Wireless STA modeEnable
Router SSIDdevolo-f4068d7414ea
Signal quality100%
IP address192.168.2.251
MAC addressF0:FE:6B:E4:EB:65
Cable modeDisable
IP address
MAC address`

Number1
Inverter serial number
AANN302019184099
Firmware version (main)V5.04Build230
Firmware version (slave)V4.13Build**_262_**
Inverter modelOmnik3000tl
Rated power3000 W
Current power55 W
Yield today13.21 kWh
Total yield1842.1 kWh
Alerts---
Last updated0 min ago

Same issue as ..."
Omnik local web-plugin crashes/hangs system" 
I hope you can help.

**Comment by sincze** [comment]
Is this still an issue with V1.0.2 ??

**Comment by sincze** [comment]
No response
