### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by gerard33** [sincze/Domoticz-Omnik-Local-Web-Plugin#3]
Thanks for sharing this code :+1:
I re-used it to work in Home Assistant -> https://community.home-assistant.io/t/omink-inverter-in-home-assistant/102455/36?u=gerard33

**Comment by sincze** [comment]
@gerard33  , did you abandon 'Domoticz' 'R us and moved to Home Assistant???? '-)

**Comment by gerard33** [comment]
Yep I did and although Domoticz was great, I like HA even better :grinning:
