### ISSUE TITLE
Kwh and W don't work :-(

### ISSUE THREAD

**Issue by Ironburn** [sincze/Domoticz-Omnik-Local-Web-Plugin#5]
Hi there,

Sorry for my bad English.

I tried to open this link: http://192.168.*.*/js/status.js
But get this message:Access Error: Site or Page Not Found
Cannot open URL

I have an omnik solar 1.5 inverter with WIFI module
And the script says inventer status is on. But me Kwh and watt don't do anything ... Anyone ideas?

**Comment by sincze** [comment]
Please login to your inverter (maybe add screenshot) to check the 'name' of
the status.js via development options of chrome. (F12) for your version.
Please also indicate installed firmware for future reference.

**Comment by Ironburn** [comment]
Hello there,

i made some screenshots of my inverter and f12 but can't find status.js.

![inverter](https://user-images.githubusercontent.com/60102973/72789725-8bd24280-3c34-11ea-9d3e-5a8ddc88bac3.png)
![inverter1](https://user-images.githubusercontent.com/60102973/72789963-ef5c7000-3c34-11ea-9e89-7766e2af968c.png)

**Comment by sincze** [comment]
Mm this should work.
Please login to your Inverter in a browser:
http://your_inverter_ip

After login execute on new tab:
http://your_inverter_ip/js/status.js

Post the results here.

**Comment by sincze** [comment]
no response
