### ISSUE TITLE
Device doesn't show in list

### ISSUE THREAD

**Issue by ghost** [sincze/Domoticz-Omnik-Local-Web-Plugin#6]
I removed the plugin when it kept crashing Domoticz. However do to problems with Z-wave i switched to the latest BETA and gave it another try. I re-added the plugin to the hardware and can see that it is running in the log file. However, no device shows up in the device list. Any suggestions?

**Comment by ghost** [comment]
UPDATE: I did a thorough job and even reinstalled Rasbian. Then the last Beta of Domoticz. Adding the plugin went smooth and its working perfectly. THX for sharing this plugin

**Comment by sincze** [comment]
Can be closed thanks to Jobbanr.
