### ISSUE TITLE
Domoticz Hardware created as "Usage"

### ISSUE THREAD

**Issue by FlorisHigh3IT** [sincze/Domoticz-Omnik-Local-Web-Plugin#7]
Works like a charm!

One thing..
The Inverter (W) is created as SubType "Electric" this will indicate in Domoticz that this device is using power instead of delivering. 

In the old script I used, the SubType "kWh" is used for both values.

**Comment by sincze** [comment]
A missed that one I think I only looked at Inverter (kWh) and put that on return.
![image](https://user-images.githubusercontent.com/5776333/77518983-f98e2b00-6e7e-11ea-909a-345bdff12db5.png)

**Comment by FlorisHigh3IT** [comment]
Yes, you can change the kWh to Return, but the Electric not. I did some researching and there is not an easy way to change this afterwards.

**Comment by sincze** [comment]
Is this still an issue or can it be closed ??

**Comment by sincze** [comment]
no response
